// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuv-nkC3jRjUXQNoqLgW7KhCuBxPAMCIY',
    appId: '1:274710880792:web:3ae3f79b108c126874596d',
    messagingSenderId: '274710880792',
    projectId: 'unihacks-c5211',
    authDomain: 'unihacks-c5211.firebaseapp.com',
    storageBucket: 'unihacks-c5211.firebasestorage.app',
    measurementId: 'G-HZLJDGHLW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ5yPvNcMn-XI1LVUY_m9cnYchwPuFhgs',
    appId: '1:274710880792:android:fde622ce98b3441074596d',
    messagingSenderId: '274710880792',
    projectId: 'unihacks-c5211',
    storageBucket: 'unihacks-c5211.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrslQPd4VCuOEsM09GvEQP4OxpO47InmM',
    appId: '1:274710880792:ios:8eedce874ab41ebd74596d',
    messagingSenderId: '274710880792',
    projectId: 'unihacks-c5211',
    storageBucket: 'unihacks-c5211.firebasestorage.app',
    iosBundleId: 'com.bondbox.bondbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrslQPd4VCuOEsM09GvEQP4OxpO47InmM',
    appId: '1:274710880792:ios:8eedce874ab41ebd74596d',
    messagingSenderId: '274710880792',
    projectId: 'unihacks-c5211',
    storageBucket: 'unihacks-c5211.firebasestorage.app',
    iosBundleId: 'com.bondbox.bondbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuv-nkC3jRjUXQNoqLgW7KhCuBxPAMCIY',
    appId: '1:274710880792:web:45febd3f8a5a050f74596d',
    messagingSenderId: '274710880792',
    projectId: 'unihacks-c5211',
    authDomain: 'unihacks-c5211.firebaseapp.com',
    storageBucket: 'unihacks-c5211.firebasestorage.app',
    measurementId: 'G-8KS3R0HG5Z',
  );
}
